### ISSUE TITLE
Home Page Design

### ISSUE THREAD

**Issue by consumedsoul** [consumedsoul/carpediemcollective#2]
Content:
- Menu - About | Schedule | Space Rental | Contact
- Hero image(s)
- Email signup

**Comment by consumedsoul** [comment]
@mspirite old skool non-responsive (doesn't work across all screen sizes) html/css... :) https://consumedsoul.github.io/carpediemcollective/

**Comment by consumedsoul** [comment]
@mspirite it's cool that you can use whatever font available on fonts.google.com now on websites... (not that the one below will be used, but cool that it's not just arial or times)

![image](https://user-images.githubusercontent.com/955153/61433513-5e54b700-a8e8-11e9-8daa-21a75dc7e781.png)

**Comment by mspirite** [comment]
Cool.
