### ISSUE TITLE
Provide Grace with Github Training

### ISSUE THREAD

**Issue by consumedsoul** [consumedsoul/carpediemcollective#8]
Background: For any web/app/code development that GH Kim LLC does going forward we'll use Github - it's basically a tool for development team to collaborate and keep their code versions stored in the cloud. Advantage of this is we can just view the entire website on a different staging area w/o impacting current site etc.

Things for you to know:
- Kanban board similar to Asana here: https://github.com/consumedsoul/carpediemcollective/projects/1
- Once we start developing web I'll show you how to submit feature requests or bug reports on https://github.com/consumedsoul/carpediemcollective/issues

**Comment by mspirite** [comment]
Okay! Thanks for working hard on this! :)

**Comment by consumedsoul** [comment]
Testing reply back from email...

*Hun Kim* | GH Kim Photography <http://ghkim.com/>

**Comment by mspirite** [comment]
Received. Replying back from email too.


*Grace Kim*
*@gracekimco <http://instagram.com/gracekimco>*
*Every single day is a gift. Carpe Diem.*

**Comment by consumedsoul** [comment]
Provided steps for submitting change requests or bug reports on https://github.com/consumedsoul/carpediemcollective/wiki/Steps-to-submit-CRs-or-Bugs
